"""
Week 5: Agent Architecture Starter Template

Build an AI agent that answers TechCorp questions using:
- Gemini 2.5 Pro LLM (free tier via Google AI API)
- SQLite database queries
- Policy document retrieval

Complete the TODO sections marked below.
"""

import json
import sqlite3
from typing import Dict, Any
import google.genai as genai
import logging
import os
from dotenv import load_dotenv # Generated by Claude Sonnet 4.6
import time # Generated by Claude Sonnet 4.6
from sentence_transformers import SentenceTransformer
from operator import itemgetter

load_dotenv() # Generated by Claude Sonnet 4.6

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")


# TASK 1: Implement the Tool base class


class Tool:
    """Base class for tools the agent can call."""

    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description

    def execute(self, **kwargs) -> str:
        """Execute the tool.

        TODO: This is implemented by subclasses.
        Each subclass should override this method.
        """
        raise NotImplementedError


# TASK 2: Implement EmployeeLookupTool


class EmployeeLookupTool(Tool):
    """Look up employee information from SQLite database."""

    def __init__(self, db_path: str):
        super().__init__("employee_lookup", "Find employee information by name or ID")
        self.db_path = db_path

    def execute(self, employee_name: str = None, employee_id: str = None) -> str:
        """Look up employee by name or ID.

        TODO: Query the employees table:
        1. Connect to SQLite database at self.db_path
        2. If employee_id is provided:
           - SELECT * FROM employees WHERE id = ?
        3. If employee_name is provided:
           - SELECT * FROM employees WHERE name LIKE ?
        4. Convert results to JSON and return
        5. If no results found, return "Employee not found"

        Args:
            employee_name: Name to search for (partial match ok)
            employee_id: ID to search for (exact match)

        Returns:
            JSON string with employee info or error message
        """
        try:
            # TODO: implement
            
            # 1. Connect to SQLite database at self.db_path
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()

            """
            2. If employee_id is provided:
               - SELECT * FROM employees WHERE id = ?
            """
            if not(employee_id == None):
                cursor.execute("SELECT * FROM employees WHERE id = ?", (employee_id,))

            """
            3. If employee_name is provided:
               - SELECT * FROM employees WHERE name LIKE ?
            """
            if not(employee_name == None):
                cursor.execute("SELECT * FROM employees WHERE name LIKE ?", (f"%{employee_name}%",))

            # 5. If no results found, return "Employee not found"
            results = cursor.fetchall()
            no_results_found = results == []
            if no_results_found:
                conn.close()
                return "Employee not found"
            
            # 4. Otherwise, convert results to JSON and return
            results_json = json.dumps(results)
            conn.close()
            return results_json

        except Exception as e:
            logger.error(f"Employee lookup error: {e}")
            conn.close()
            return f"Error: {str(e)}"


# TASK 3: Implement PolicySearchTool


class PolicySearchTool(Tool):
    """Search policy documents by keyword."""

    def __init__(self):
        super().__init__("policy_search", "Search policy documents by keyword or topic")
        # TODO: Load data/documents.json
        self.documents = []

        # 1. Load documents (from JSON file in data/ folder)
        with open("data/documents.json") as f:
            self.documents = json.load(f)

        # Load a sentence transformer model, embed the contents of all the documents, and map the embeddings to their corresponding docs
        self.transformer = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
        self.doc_embeddings = []
        for doc in self.documents:
            doc_embedding = self.transformer.encode(doc["content"].lower())
            self.doc_embeddings.append((doc_embedding, doc))


    def execute(self, query: str, limit: int = 5, baseline: bool = False) -> str:
        """Search policies by keyword.

        TODO: Implement policy search:
        1. Load documents (from JSON file in data/ folder)
        2. Search documents by keyword match
        3. Return top-N matching documents
        4. Include title and snippet (first 500 chars) for each

        Args:
            query: Search term
            limit: Max results to return

        Returns:
            Formatted string with matching documents
        """
        try:
            # TODO: implement

            # 2. Search documents by keyword match
            matches = None 
            
            if baseline:
                matches = [doc for doc in self.documents if query.lower() in doc["content"].lower()]
                # If there are no matches, return "No matching policy documents found"
                if len(matches) == 0:
                    return "No matching policy documents found"

                """
                3. Return top-N matching documents AND 
                4. Include title and snippet (first 500 chars) for each
                """
                top_n_matches = matches[:limit]
                top_n_matches_title_to_snippet = {}
                for match in top_n_matches:
                    top_n_matches_title_to_snippet[match["title"]] = match["content"][:500]
                title_snippet_pairs = top_n_matches_title_to_snippet.items()
                title_snippet_str_pairs = []
                for pair in title_snippet_pairs:
                    title_snippet_str_pairs.append(": ".join(pair))
                results = "\n".join(title_snippet_str_pairs)
                return results

            query_embedding = self.transformer.encode(query.lower())
            query_doc_similarities = []
            for doc_embedding in self.doc_embeddings:
                query_doc_similarity = self.transformer.similarity(query_embedding, doc_embedding[0])
                query_doc_similarities.append((doc_embedding, query_doc_similarity.item()))
            sorted_match_pairs = sorted(query_doc_similarities, key=itemgetter(1), reverse=True)
            """
            3. Return top-N matching documents AND 
            4. Include title and snippet (first 500 chars) for each
            """
            top_n_sorted_match_pairs = sorted_match_pairs[:limit]
            top_n_matches = []
            for match in top_n_sorted_match_pairs:
                doc_embedding_pair = match[0]
                doc_corresponding_to_embedding = doc_embedding_pair[1]
                top_n_matches.append(doc_corresponding_to_embedding)
            top_n_matches_title_to_snippet = {}
            for match in top_n_matches:
                top_n_matches_title_to_snippet[match["title"]] = match["content"][:500]
            title_snippet_pairs = top_n_matches_title_to_snippet.items()
            title_snippet_str_pairs = []
            for pair in title_snippet_pairs:
                title_snippet_str_pairs.append(": ".join(pair))
            results = "\n".join(title_snippet_str_pairs)
            return results
        except Exception as e:
            logger.error(f"Policy search error: {e}")
            return f"Error: {str(e)}"


# TASK 4: Implement ExpenseQueryTool


class ExpenseQueryTool(Tool):
    """Query expense policies and approval limits."""

    def __init__(self):
        super().__init__("expense_query", "Query expense approval limits by role")
        # TODO: load data/policies.json into the documents attribute
        self.policies = {}

        # 1. Load policies (from JSON file in data/ folder)
        with open("data/policies.json") as f:
            self.policies = json.load(f)

    def execute(self, role: str) -> str:
        """Query expense approval limit for a given role.

        TODO: Implement expense lookup:
        1. Look up role in self.policies["expense"]["approval_limits"]
        2. Return: "Approval limit for {role}: ${amount}"
        3. If role not found, return "Role not found: {role}"

        Args:
            role: Employee role (ic1_ic2, ic3, manager, director, vp)

        Returns:
            String with approval limit for the given role
        """
        try:
            # TODO: implement

            # 1. Look up role in self.policies["expense"]["approval_limits"]
            role_looked_up = self.policies["expense"]["approval_limits"].get(role)

            # 3. If role not found, return "Role not found: {role}"
            if role_looked_up == None:
                return f"Role not found: {role}"

            # 2. Return: "Approval limit for {role}: ${amount}"
            return f"Approval limit for {role}: ${role_looked_up}"

        except Exception as e:
            logger.error(f"Expense query error: {e}")
            return f"Error: {str(e)}"


# TASK 5: Implement the Agent class


class Agent:
    """AI agent that answers questions using Gemini LLM + tools."""

    def __init__(self, db_path: str, api_key: str = None):
        """Initialize the agent.

        TODO:
        1. Get API key from parameter or GOOGLE_API_KEY environment variable
        2. Raise ValueError if no API key provided
        3. Initialize Google GenAI client with api_key
        4. Initialize all tools (EmployeeLookup, PolicySearch, ExpenseQuery)
        5. Initialize token and cost tracking variables

        Args:
            db_path: Path to SQLite database
            api_key: Google AI API key (or use GOOGLE_API_KEY env var)
        """
        self.db_path = db_path
        self.api_key = api_key or GOOGLE_API_KEY

        if not self.api_key:
            raise ValueError(
                "GOOGLE_API_KEY not set. Get free key at: "
                "https://aistudio.google.com/app/apikey"
            )

        # TODO: Initialize Google GenAI client
        self.client = genai.Client(api_key=self.api_key)

        # TODO: Initialize tools dictionary
        self.tools = {
            "employee_lookup": EmployeeLookupTool(db_path),
            "policy_search": PolicySearchTool(),
            "expense_query": ExpenseQueryTool(),
        }

        # TODO: Initialize metrics
        self.input_tokens = 0
        self.output_tokens = 0
        self.token_count = 0
        self.total_cost = 0.0
        self.queries_run = 0

    def _build_system_prompt(self, user_role: str, user_query: str) -> str:
        """Build system prompt describing available tools.

        TODO: Create a prompt that:
        1. Describes the agent's purpose
        2. Lists all available tools with descriptions
        3. Explains how to use them
        4. Sets the user's role context

        Returns:
            System prompt string
        """
        # TODO: implement
        system_prompt = f""" 
        You are an enterprise knowledge assistant for a company called TechCorp that has employees across engineering, HR, finance, operations, sales, and compliance. Your purpose is to answer any questions they have given the following available tools:

        1) employee_lookup - A tool that looks up an employee's information from a SQLite database given a name (employee_name) and/or an id (employee_id). If you provide a name, it needs to be a partial match for the actual name of the employee you want to look up. If you provide an id, it needs to be an exact match for the actual id of the employee you want to look up. For each employee in the employees tab of the SQLite database, the following types of information can be accessed (some of these values might be missing for some employees): id, name, email, department_id, department_name, job_level, title, salary, ssn, address, phone, hire_date, manager_id, bonus_eligible, stock_options. The parameters for this tool are employee_name: str (the name of the employee; default value of None), employee_id: str (the employee’s id; default value of None).

        2) policy_search - A tool that searches policy documents by keyword or topic given a question to answer (query - already known no need to worry about providing this value). This tool loads a json file that is a list of dictionaries (each representing a document) where each dictionary has the document’s title as well as the document’s content, determines the top N matching documents (where N is determined by the limit parameter) for the user_query, and returns a formatted string with information for each of the top N matching documents (for each of these documents, the title and a 500-character preview of the content is returned in a formatted string). The parameters to focus on for this tool are user_query: str (the question to answer; no default value) and limit: int (the value for N in the context of determining the top N matching documents; default value of 5 to indicate top 5 matching documents).

        3) expense_query - A tool that looks up expense approval limits by role given a passed in role (role - already known no need to worry about providing this value). Valid roles to pass in are ic1_ic2, ic3, manager, director, vp. The parameter for this tool is role: str (the passed in role name; no default value).

        Here is the question that the user wants to ask: {user_query}. For context, this user's role is the following: {user_role}.

        Given this question, please state each of the tools that you believe should be used to answer these questions and report the recommended parameter values for each tool. I would like your response to be formatted as follows:

        Necessary Tool 1 Name***
        Necessary Tool 1 Name param1=x*param1*
        Necessary Tool 1 Name param2=y*param2*
        Necessary Tool 1 Name Done
        ….
        Necessary Tool 2 Name***
        Necessary Tool 2 Name param1=x*param1*
        Necessary Tool 2 Name param2=y*param2*
        Necessary Tool 2 Name Done
        ….
        """
        return system_prompt

    def query(self, user_query: str, user_role: str = "engineer") -> Dict[str, Any]:
        """Answer a question using LLM + tools.

        TODO: Implement the reasoning loop:

        1. Call _build_system_prompt(user_role) to build the system prompt

        2. Call Gemini LLM with system prompt + user question
           - self.client.models.generate_content(model="gemini-3.1-flash-lite", ...)

        3. Parse LLM response to identify tool calls
           - Check if response mentions any tool names
           - Extract parameters from response

        4. Execute tools with extracted parameters
           - tool.execute() with parameters
           - Collect results

        5. Synthesize final answer
           - Pass tool results back to LLM
           - Get final answer

        6. Track tokens and cost
           - Count tokens in request/response
           - Calculate cost: (tokens / 1_000_000) * rate
           - Update totals

        Args:
            user_query: The question to answer
            user_role: User's role (for access control in future weeks)

        Returns:
            Dict with keys:
            - "answer": str - the response
            - "tokens_used": int - total tokens
            - "cost": float - cost in dollars
            - "role": str - user role
        """
        logger.info(f"Processing query: {user_query}")

        # TODO: implement agent query logic

        # 1. Call _build_system_prompt(user_role) to build the system prompt
        system_prompt = self._build_system_prompt(user_role, user_query)
        #print("system_prompt:")
        #print(f"{system_prompt}")
        #print("---------------------------------------------------")

        # Track the number of attempts the agent has made for getting the necessary information for synthesizing the final answer.
        num_tries = 0

        while True:
            num_tries += 1

            # 2. Call Gemini LLM with system prompt + user question
            llm_response = self.client.models.generate_content(model="gemini-3.1-flash-lite", contents=system_prompt)
            #print("llm_response:")
            #print(f"{llm_response.text}")
            #print("---------------------------------------------------")

            """
            3. Parse LLM response to identify tool calls
            - Check if response mentions any tool names
            - Extract parameters from response
            """
            tools_in_llm_response = []
            for tool in self.tools:
                if tool in llm_response.text.lower():
                    tools_in_llm_response.append(tool)
            tools_in_llm_response_params = {}
            for tool in tools_in_llm_response:
                if tool == "employee_lookup":
                    try:
                        employee_name_start_index = llm_response.text.index("employee_name=") + len("employee_name=")
                        employee_name_end_index = llm_response.text.index("*employee_name*")
                        employee_name = llm_response.text[employee_name_start_index:employee_name_end_index]
                    except ValueError:
                        employee_name = None

                    try:
                        employee_id_start_index = llm_response.text.index("employee_id=") + len("employee_id=")
                        employee_id_end_index = llm_response.text.index("*employee_id*")
                        employee_id = llm_response.text[employee_id_start_index:employee_id_end_index]
                    except ValueError:
                        employee_id = None

                    tools_in_llm_response_params[tool] = [employee_name, employee_id]
                elif tool == "policy_search":
                    query = user_query # Already provided in the method signature

                    try:
                        limit_start_index = llm_response.text.index("limit=") + len("limit=")
                        limit_end_index = llm_response.text.index("*limit*")
                        limit = int(llm_response.text[limit_start_index:limit_end_index])
                    except ValueError:
                        limit = 5

                    tools_in_llm_response_params[tool] = [query, limit]
                elif tool == "expense_query":
                    """
                    role_start_index = llm_response.text.index("role=") + len("role=")
                    role_end_index = llm_response.text.index("*role*")
                    role = llm_response[role_start_index:role_end_index]
                    """

                    tools_in_llm_response_params[tool] = user_role # Already provided in the method signature

            """
            4. Execute tools with extracted parameters
            - tool.execute() with parameters
            - Collect results
            """
            results = {}
            for tool in tools_in_llm_response:
                if tool == "employee_lookup":
                    tool_result = self.tools[tool].execute(employee_name=tools_in_llm_response_params[tool][0], employee_id=tools_in_llm_response_params[tool][1])
                    results[tool] = tool_result
                elif tool == "policy_search":
                    tool_result = self.tools[tool].execute(query=tools_in_llm_response_params[tool][0], limit=tools_in_llm_response_params[tool][1])
                    results[tool] = tool_result
                elif tool == "expense_query":
                    tool_result = self.tools[tool].execute(role=tools_in_llm_response_params[tool])
                    results[tool] = tool_result

            """
            5. Synthesize final answer
            - Pass tool results back to LLM
            - Get final answer
            """
            final_answer_check_prompt = f"Here are the results from using the tools you recommended along with their recommended parameters: {results}. Are these results sufficient for answering the user's question {user_query} given their role {user_role} at TechCorp? Format your response as a one word response: True or False."
            final_answer_check = self.client.models.generate_content(model="gemini-3.1-flash-lite", contents=final_answer_check_prompt)
            #print("final_answer_check:")
            #print(f"{final_answer_check.text}")
            #print("---------------------------------------------------")

            if "False" in final_answer_check.text and num_tries < 3:
                """
                system_prompt_token_count = len(system_prompt)
                final_answer_check_prompt_token_count = len(final_answer_check_prompt)
                llm_response_token_count = len(llm_response)
                final_answer_check_token_count = len(final_answer_check)
                self.input_tokens += (system_prompt_token_count + final_answer_check_prompt_token_count)
                self.output_tokens += (llm_response_token_count + final_answer_check_token_count)
                """
                system_prompt_token_count = llm_response.usage_metadata.prompt_token_count
                llm_response_token_count = llm_response.usage_metadata.candidates_token_count
                final_answer_check_prompt_token_count = final_answer_check.usage_metadata.prompt_token_count
                final_answer_check_token_count = final_answer_check.usage_metadata.candidates_token_count
                self.input_tokens += (system_prompt_token_count + final_answer_check_prompt_token_count)
                self.output_tokens += (llm_response_token_count + final_answer_check_token_count)
                continue

            final_answer_prompt = f"Here are the results from using the tools you recommended along with their recommended parameters: {results}. Would you be able to synthesize these results into a final answer for the user in paragraph form? Please make sure your final answer does not incorporate any irrelevant information."
            final_answer = self.client.models.generate_content(model="gemini-3.1-flash-lite", contents=final_answer_prompt)
            #print("final_answer:")
            #print(f"{final_answer.text}")

            """
            6. Track tokens and cost
            - Count tokens in request/response
            - Calculate cost: (tokens / 1_000_000) * rate
            - Update totals
            """
            """
            system_prompt_token_count = len(system_prompt)
            final_answer_check_prompt_token_count = len(final_answer_check_prompt)
            final_answer_prompt_token_count = len(final_answer)
            llm_response_token_count = len(llm_response)
            final_answer_check_token_count = len(final_answer_check)
            final_answer_token_count = len(final_answer)
            self.input_tokens += (system_prompt_token_count + final_answer_check_prompt_token_count + final_answer_prompt_token_count)
            self.output_tokens += (llm_response_token_count + final_answer_check_token_count + final_answer_token_count)
            """
        
            system_prompt_token_count = llm_response.usage_metadata.prompt_token_count
            llm_response_token_count = llm_response.usage_metadata.candidates_token_count
            final_answer_check_prompt_token_count = final_answer_check.usage_metadata.prompt_token_count
            final_answer_check_token_count = final_answer_check.usage_metadata.candidates_token_count
            final_answer_prompt_token_count = final_answer.usage_metadata.prompt_token_count
            final_answer_token_count = final_answer.usage_metadata.candidates_token_count
            self.input_tokens += (system_prompt_token_count + final_answer_check_prompt_token_count + final_answer_prompt_token_count)
            self.output_tokens += (llm_response_token_count + final_answer_check_token_count + final_answer_token_count)
            self.total_cost = self._estimate_query_cost(self.input_tokens, self.output_tokens)
            self.token_count = self.input_tokens + self.output_tokens
            break
        
        # Increment the number of queries run.
        self.queries_run += 1

        return {
            "answer": final_answer.text,
            "tokens_used": self.token_count,
            "cost": self.total_cost,
            "role": user_role,
        }

    def _estimate_query_cost(self, input_tokens: int, output_tokens: int) -> float:
        """Calculate cost based on tokens.

        Gemini 2.5 Pro pricing:
        - Input: $0.075 per 1M tokens
        - Output: $0.3 per 1M tokens
        """
        input_cost = (input_tokens / 1_000_000) * 0.075
        output_cost = (output_tokens / 1_000_000) * 0.3
        return input_cost + output_cost

    def get_metrics(self) -> Dict[str, Any]:
        """Return performance metrics.

        TODO: Return dict with:
        - total_queries: number of queries processed
        - total_tokens: cumulative tokens used
        - total_cost: cumulative cost in dollars
        - avg_cost_per_query: average cost per query
        """
        # TODO: implement
        return {
            "total_queries": self.queries_run,
            "total_tokens": self.token_count,
            "total_cost": self.total_cost,
            "avg_cost_per_query": self.total_cost/self.queries_run if self.queries_run > 0 else 0.0,
        }


# TASK 6: Test your implementation

if __name__ == "__main__":
    """Quick test of agent functionality."""
    import sys

    try:
        # Initialize agent
        agent = Agent("data/techcorp.db", api_key=GOOGLE_API_KEY)
        print("Agent initialized successfully")
        print("---------------------------------------------------------------------------------------------")

        # Test 10 queries.

        # Query 1
        print("\nTesting Query #1: 'What is the travel policy?'")
        result1 = agent.query(user_query="What is the travel policy?")
        print(f"Answer: {result1['answer']}")
        print(f"Tokens: {result1['tokens_used']}")
        print(f"Cost: ${result1['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")
        

        # Query 2
        print("\nTesting Query #2: 'What is Brian Yang's position at TechCorp?'")
        result2 = agent.query(user_query="What is Brian Yang's position at TechCorp?")
        print(f"Answer: {result2['answer']}")
        print(f"Tokens: {result2['tokens_used']}")
        print(f"Cost: ${result2['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        
        # Query 3
        print("\nTesting Query #3: 'I am a manager at TechCorp. Can you tell me what my expense approval limit is?'")
        result3 = agent.query(user_query="I am a manager at TechCorp. Can you tell me what my expense approval limit is?", user_role="manager")
        print(f"Answer: {result3['answer']}")
        print(f"Tokens: {result3['tokens_used']}")
        print(f"Cost: ${result3['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 4
        print("\nTesting Query #4: 'What is the Paid Time Off policy?'")
        result4 = agent.query(user_query="What is the Paid Time Off policy?")
        print(f"Answer: {result4['answer']}")
        print(f"Tokens: {result4['tokens_used']}")
        print(f"Cost: ${result4['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 5
        print("\nTesting Query #5: 'Can you summarize the information we have on the System Architecture Overview?'")
        result5 = agent.query(user_query="Can you summarize the information we have on the System Architecture Overview?")
        print(f"Answer: {result5['answer']}")
        print(f"Tokens: {result5['tokens_used']}")
        print(f"Cost: ${result5['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 6
        print("\nTesting Query #6: 'What are the Sales Territory 2 Guidelines?'")
        result6 = agent.query(user_query="What are the Sales Territory 2 Guidelines?")
        print(f"Answer: {result6['answer']}")
        print(f"Tokens: {result6['tokens_used']}")
        print(f"Cost: ${result6['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 7
        print("\nTesting Query #7: 'I am a vp at TechCorp. Can you tell me what my expense approval limit is?'")
        result7 = agent.query(user_query="I am a vp at TechCorp. Can you tell me what my expense approval limit is?", user_role="vp")
        print(f"Answer: {result7['answer']}")
        print(f"Tokens: {result7['tokens_used']}")
        print(f"Cost: ${result7['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 8
        print("\nTesting Query #8: 'What is the remote work policy?'")
        result8 = agent.query(user_query="What is the remote work policy?")
        print(f"Answer: {result8['answer']}")
        print(f"Tokens: {result8['tokens_used']}")
        print(f"Cost: ${result8['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 9
        print("\nTesting Query #9: 'I am the VP at TechCorp and want to see what information do we have on 30 (employee_id). Give me a quick rundown on this employee.'")
        result9 = agent.query(user_query="I am the VP at TechCorp and want to see what information do we have on 30 (employee_id). Give me a quick rundown on this employee.")
        print(f"Answer: {result9['answer']}")
        print(f"Tokens: {result9['tokens_used']}")
        print(f"Cost: ${result9['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Query 10
        print("\nTesting Query #10: 'I am a director at TechCorp. Can you tell me what my expense approval limit is?'")
        result10 = agent.query(user_query="I am a director at TechCorp. Can you tell me what my expense approval limit is?", user_role="director")
        print(f"Answer: {result10['answer']}")
        print(f"Tokens: {result10['tokens_used']}")
        print(f"Cost: ${result10['cost']:.6f}")
        time.sleep(60) # Generated by Claude Sonnet 4.6
        print("---------------------------------------------------------------------------------------------")

        # Check metrics
        metrics = agent.get_metrics()
        print(f"\nMetrics: {metrics}")
        print("---------------------------------------------------------------------------------------------")
        

    except Exception as e:
        print(f"Error: {e}")
        logger.exception("Error during test")
        sys.exit(1)
